![iSA logo](../iSA_logo.png)
### Materiały do zajęć Statystyka
#### Kurs Junior Data Scientist

**Wojciech Artichowicz**

**W eksperymencie bada ilość wydzielonego produktu w wyniku reakcji chemicznej. Wykonano $n=60$ niezależnych doświadczeń i otrzymano z nich średnią  $\bar{x}=46$ g oraz odchylenie $s=13$ g. Przyjmując współczynnik ufności $1-\alpha=0,99$ oszacować metodą przedziałową średnią wagę wydzielonej substancji.**

In [1]:
import numpy as np
import scipy.stats as st

In [2]:
# Utworzenie zmiennych przechowujących dane:
x=46
s=13
a=1-0.99
n=60

In [3]:
# Utworzenie obiektu reprezentującego rozkład normalny standardyzowany:
NormalDistribution = st.norm(0,1)

Odczytanie kwantyli (funkcja ppf) rozkładu normalnego standardyzowanego dla wartości $\frac{\alpha}{2}$ oraz $1-\frac{\alpha}{2}$:

In [4]:
u=NormalDistribution.ppf([a/2,1-a/2])
u

array([-2.5758293,  2.5758293])

Obliczenie przedziałów ufności. Wstawienie do wzoru:
$$CI_{\mu} = \left( \bar{x} + u_{\frac{\alpha}{2}}\frac{s}{\sqrt{n}}; \bar{x} + u_{1-\frac{\alpha}{2}}\frac{s}{\sqrt{n}}\right)$$

In [5]:
CIm = x + u*s/np.sqrt(n)
print(CIm)

[41.67700427 50.32299573]


**Dla danych z zadania powyżej. zbuduj przedział ufności dla odchylenia standardowego.**

In [6]:
# Utworzenie obiektu reprezentującego rozkład chi kwadrat z n-1 stopniami swobody
ChiSquareDistribution = st.chi2(n-1)

In [7]:
# obliczenie kwantyli tego rozkładu dla danych wartości a/2 i 1-a/2
q=ChiSquareDistribution.ppf([a/2,1-a/2])
q

array([34.77043403, 90.71529311])

Obliczenie przedziałów ufności wg wzoru (zwróć uwagę, na kolejność kwantyli we wzorze)
$$CI_\sigma = \left(\sqrt{\frac{(n-1)s^2}{\chi_{1-\frac{\alpha}{2}}^2}} ; \sqrt{\frac{(n-1)s^2}{\chi_{\frac{\alpha}{2}}^2}} \right)$$

In [8]:
CIs = np.sqrt((n-1)*s**2/q[::-1])
print(CIs)

[10.4840505  16.93418509]


**W ankiecie wzięło udział $n=1000$ respondentów. Pytano ich czy palą regularnie. 20% z nich odpowiedziało „tak”. Znajdź przedziały ufności dla proporcji osób palących w populacji generalnej. przyjmij poziom ufności
$1-\alpha = 0,99$.**

In [9]:
n=1000
p=20/100
a=1-0.99


# Utworzenie obiektu reprezentującego rozkład normalny standardyzowany:
NormalDistribution = st.norm(0,1)

In [10]:
u=NormalDistribution.ppf([a/2,1-a/2]) #odczytanie kwantyli
u

array([-2.5758293,  2.5758293])

In [11]:
CIp = p+u*np.sqrt(p*(1-p)/n)
print(CIp)

[0.16741805 0.23258195]
